### ISSUE TITLE
How are incomplete files handled?

### ISSUE THREAD

**Issue by ragesoss** [kjschiroo/python-mwdumps#1]
I've been running this to get a recent dump, and it usually eventually dies with an error like `urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 1332182705 out of 1997066159 bytes>`.

When I restart it, will it re-download the incomplete file or validate the checksums or anything like that, or does cleanup of bad files need to be done manually?

**Comment by kjschiroo** [comment]
Right now it just restarts everything, so not the most optimal strategy, but all files will be correct at the end. I'm reworking it right now to check shas. Are you using the command-line? I'm thinking of making a breaking change to `dumps.py` so I want to make sure you aren't depending on it.

**Comment by kjschiroo** [comment]
Checkout the [1_sha_check](https://github.com/kjschiroo/python-mwdumps/tree/1_sha_check) branch. That should have support for validating the checksums and only re-downloading the files that are needed.

**Comment by ragesoss** [comment]
@kjschiroo cool. Yeah, I was using it from command line. I realized I was trying to download everything, instead of just the .gz metadata files that I need for TopicContribs, so I got it to run to completion without error. (Trying to re-run your analysis for recent terms.)

Next time I'll use that sha branch (if it's not merged by then).

**Comment by kjschiroo** [comment]
It's now been merged in. I've also made a couple updates and posted in on pypi.
Changes:
- Checksums now being checked and file downloads restarted if needed.
- Can now be installed with `pip install mwdumps`
- Can now be run using just `mwdumps` on the command-line.
Closing this issue.
